### ISSUE TITLE
feature ask..... save tabs rather than open in pc

### ISSUE THREAD

**Issue by JaziTricks** [machinateur/android-chrome-tab-transfer#10]
world it be possible?

thing is, Chrome refuses to do save all tabs in Android. and would be a great app to have.

thanks :)

**Comment by machinateur** [comment]
I think I won't develop this into an app. That's if I understand your idea correctly...

The main purpose of this tool is to help migrate a larger amount of tabs from an android phone's chrome browser more time-effeicient.

The method used for transfer is not "safe" for use in the wild, in my opinion. Using debugging capabilities of mobile devices should not be done lightly.

That said, in a sense, the tool already "saves" the tabs. Reopening them is currently only possible on Linux and Mac (or Windows using MINGW64) using a generated script.

Also, the `.md` file can be moved to a private [gist](https://gist.github.com) to make it available to you as formatted list (the same is possible using any markdown editor/viewer).

You can of course always access the raw JSON in any browser on the computer (using the URL printed to the terminal) and use the list in another way. The raw JSON is also saved on-disk.
