### ISSUE TITLE
iOS Support

### ISSUE THREAD

**Issue by machinateur** [machinateur/android-chrome-tab-transfer#13]
I'm planning to add full support for iOS (Chrome and Safari). Transferring tabs from apple devices should be possible, just like on android, via the ~~Chrome DevTools Protocol~~ WebKit DevTools Protocol. I'll have to so some research prior to implementing it thought. Here are some resources:

- ["Remote Debugging for Chrome iOS (and Safari)" on StackOverflow](https://stackoverflow.com/a/33344973/20205180)
- ["iOS WebKit Debug Proxy" Repository by Google](https://github.com/google/ios-webkit-debug-proxy)

The update will affect how the tool's code is currently structured. Furthermore the name of this very repository will be subject to change after this, to reflect the extended support. The new name will be ~~`chrome-tab-transfer`~~ `tab-transfer`.

For now, this is only a _planned_ feature, since I'll have to get my hands onto a real-life iPhone first, but the whole thing should still work the same, regarding the basic steps (i.e. check executable, launch adb/iwdp proxy, download the tabs, write output files and finally do some cleanup).

It might make sense to keep some backwards compatibility with the current command, to keep automation scripts working correctly.

**Comment by machinateur** [comment]
Update on this: I've started the implementation of the described feature.

**Comment by machinateur** [comment]
Hey @rijnhard and @devnll,

Hope this finds you well. Since you've contributed in the past, I'd like to ask you kindly: Would you be willing to review and test the changes in the #33 branch? This is the long-awaited iOS support with some fundamental changes.

I'd like to release them as part of `0.5.0` soon-ish. Once tested properly, I'll build the `.phar` and create an installer for windows, before merging.

Best regards

**Comment by rijnhard** [comment]
I can test the android side, but I don't own any iOS devices...

**Comment by machinateur** [comment]
No worries, I tested iOS and Android transfer/restore on my devices already. Everything worked fine. But I might be blind to certain inconsistencies and such.
