### ISSUE TITLE
Not all tabs are transferred when there are 1000+ tabs open

### ISSUE THREAD

**Issue by UtopianElectronics** [machinateur/android-chrome-tab-transfer#19]
I had about 1330 tabs open in Chrome on my Android device, I noted the number after closing all the tabs, and I had previously noticed that Chrome's own sync feature doesn't sync all the open tabs when the number of them gets too large, so I tried this tool and noticed that only 817 tabs are recorded in the files created by this tool. Similar to the issue with Google's tab syncing feature.

Is this fixable or it's a limitation of the Chrome browser?

**Comment by machinateur** [comment]
Hey there,

to my knowledge there is no limitation on the number of tabs that can be transferred. I do know the problem with Chrome's sync feature, which was one of the reasons I created this tool.

In #18 a user reportedly did an export of >1k tabs. I have not tried to export that many tabs myself, only about 300-400.

It's really hard to reproduce such problems, as there are many unknowns in the game - most notably the Chrome version, Android version, ADB version, etc.

I noticed that blank tabs (ones that have not navigated to any webpage) were not exported in the past. I didn't read about any time-factor being of importance for the [tab list endpoint](https://chromedevtools.github.io/devtools-protocol/#endpoints), which is used by the tool. I'll have another look, but this is probably not something I can further investigate without more information.

And even then, it can take some time to set up testing.

So I'll leave this issue open for now, but I can't say when I will be able to test something like this.

**Comment by UtopianElectronics** [comment]
There was no blank tabs among them, or maybe just a few ones. I'll try again later with 1.3K open tabs and give some new feedback.

**Comment by UtopianElectronics** [comment]
Tried again today with 1623 open tabs, and this time it was successful! However, this time, I had Google Chrome open on my Android device (and on my computer) during the transfer. Does this affect the transfer? I can't remember if it was open last time.

**Comment by machinateur** [comment]
No, having chrome open while transferring tabs should have no effect. While chrome's integrated development tools can be used to directly interact and debug the mobile browser tabs, it does not affect connection stability or success.

The mobile chrome browser should be opened, though, at the time of transfer, to guarantee successfully fetching the information from it's debug endpoints.
