### ISSUE TITLE
Chrome Beta support?

### ISSUE THREAD

**Issue by devnll** [machinateur/android-chrome-tab-transfer#2]
Thanks for sharing this!

I have both Chrome and Chrome Beta running on my phone. Is it possible to get the tabs from Chrome Beta instead of regular Chrome?

**Comment by machinateur** [comment]
Ok, this is an interesting question...

I've done some quick research on the underlying workings of the forwarding ability of `adb`. So, according to [the docs](http://adbcommand.com/adbshell#networking-commands) it uses unix sockets.

This is related to the forwarding done by `copy-tabs` internally using `adb forward`.

https://github.com/machinateur/android-chrome-tab-transfer/blob/933bc81512f778ee6df68f7e7baf84132ac84752/src/Command/CopyTabsCommand.php#L92-L97

The socket part is `localabstract:chrome_devtools_remote`, which is the one exposed by the "normal" chrome version on android.

It appears the chrome beta on the device does expose such a socket too. I think you can safely follow [this blog post](https://web.archive.org/web/20211019233047/https://www.girish.in/how-remote-debugging-works-in-chrome/) to find out what socket you are looking for. It should look just like the "normal" one, but with a number appended to its name. The relevant excerpt:

> **Finding the unix domain socket**
>
> `/proc/net/unix` contains the list of unix domain sockets. Chrome creates sockets with `_devtools_remote` somewhere in the name of the socket (see [devtools_adb_bridge.cc](https://web.archive.org/web/20140314183726/https://chromium.googlesource.com/chromium/src/+/master/chrome/browser/devtools/devtools_adb_bridge.cc)).
>
> You can view it by using the following command on the host:
>
> ```bash
> adb shell cat /proc/shell/unix | grep _devtools_remote
> ```
> The output should be something like this:
>
> ```
> 00000000: 00000002 00000000 00010000 0001 01 107909 @chrome_devtools_remote_8985
> 00000000: 00000002 00000000 00010000 0001 01 87977 @chrome_devtools_remote
> ```
>
> There are two sockets listed because I have Chrome Beta and Chrome running at the same time. The ‘@’ in front of the socket name implies an [abstract socket](https://web.archive.org/web/20140314183726/http://man7.org/linux/man-pages/man7/unix.7.html).

Sadly (my bad actually) the socket name cannot be changed from the cli when calling the `copy-tabs` command in the current version. So for now you'll have to edit the hardcoded value and exchange it for the one yielded by the above `adb shell` call. PRs always welcome.

Also, there is always `chrome://inspect/#devices` to the rescue and for checking what's going on.

**Comment by devnll** [comment]
Awesome, thank you!

I did have to make one small modification - it seems that `/proc/shell/unix` doesn't exist on my phone so instead I had to do:

```
adb shell cat /proc/net/unix | strings | grep -a _devtools_remote
```

This gave the desired output:

```
0000000000000000: 00000002 00000000 00010000 0001 01 332286 @chrome_devtools_remote
0000000000000000: 00000002 00000000 00010000 0001 01 332568 @chrome_devtools_remote_6408
```

So I was able to set up the forward using:

```
adb -d forward tcp:9223 localabstract:chrome_devtools_remote_6408
```

and then got the json from http://localhost:9223/json/list

I'll submit a PR that adds the socket name as a cli argument to `copy-tabs` in case anyone else might find this useful :)
