### ISSUE TITLE
Transferring tab history? 

### ISSUE THREAD

**Issue by UtopianElectronics** [machinateur/android-chrome-tab-transfer#20]
Google's tab sync feature remembers each tab's history, which is a convenient thing to have. This tool doesn't seem to do this. Is there any way to add this functionality to it?

**Comment by machinateur** [comment]
I don't think this is possible. The [CDP HTTP endpoints](https://chromedevtools.github.io/devtools-protocol/#endpoints) do not seem to provide such extended information, though it might be available through some web-socket interaction.

Either way, this would be something beyond the targeted functionality of this tool, which is to be able to transfer the currently opened tabs from an android phone to the pc and back.

**Comment by UtopianElectronics** [comment]
I see. Is there any way to at least identify the tabs that have a history and close the ones that had been opened directly (without any history), and sync the remaining tabs using Google's own syncing?

**Comment by machinateur** [comment]
As said, to my knowledge there is no way to access the history directly. At least, there is no documented way of reading it programmatically.

I guess that's a design decision, probably for security/privacy reasons.

Well, at least for mobile browsers, over CDP with USB debugging.

It seems possible though, to use [puppeteer](https://pptr.dev/) (a framework chrome automation and testing) in conjunct with the functinality provided to browser extensions through the [`history` API](https://developer.chrome.com/docs/extensions/reference/history/#method-search).

I haven't tested this, but in theory, one should be able to [inject extension code via the puppeteer API](https://pptr.dev/guides/chrome-extensions) calls into the browser tabs. Some examples of what the `history` extension API can do, can be found [here](https://chromium.googlesource.com/chromium/src/+/refs/heads/main/chrome/test/data/extensions/api_test/history/regular/). The starting point would probably be the [Page API](https://pptr.dev/api/puppeteer.page) to call the extension code and the [BrowserContext API](https://pptr.dev/api/puppeteer.browsercontext).

But keep in mind, it will only be possible to do these things on desktop browsers - iirc the mobile version of Chrome does not support extensions.

Let me know if you are able to find out more about it.
