### ISSUE TITLE
On what IDE can I run all the commands you mentioned in the readme file?

### ISSUE THREAD

**Issue by dluigi** [machinateur/android-chrome-tab-transfer#23]
On what IDE can I run all the commands you mentioned in the readme file?

**Comment by dluigi** [comment]
Why am I getting this error:
https://prnt.sc/3y7n1Tw8QuYS

**Comment by machinateur** [comment]
This is the message displayed, when the android debug bridge (adb) is not installed in a way, that is detectable for the program.

If you've already installed these debug tools on your system, the directory is probably not yet listed on the `%PATH%` environment variable.

That's important, as the tool will call it as an shell/cmd command, which is only possible if the executable can be found in any directory path listed on said variable.

But in general, the tool does not require a specific IDE to run, in fact no IDE at all. Only PHP and adb are hard dependencies, as well as composer, which is the package manager used to install the required PHP libraries.

**Comment by machinateur** [comment]
I'll close this, due to inactivity.
