### ISSUE TITLE
Suggestion: Code refactor - subcommands

### ISSUE THREAD

**Issue by rijnhard** [machinateur/android-chrome-tab-transfer#25]
It's not obvious how you need to use the reopen script. 

the suggestion is to refactor the command into 2 subcommand that will share most of their code:
* `export` basically the current functionality
* `reopen-android` this will replace the generated reopen script, but will handle the adb forwarding setup just like the export, which reopen doesn't currently do.

**Comment by machinateur** [comment]
Hello @rijnhard, thanks for suggesting this as a change.

---

And it's actually what's currently planned as an in-between step: Every now and then I'm looking into efforts to support iOS with this tool. I haven't yet gotten around to push any working code in that regard, but if and when I'm able to make it work, this is the most logical approach to separate android and iOS commands (steps will likely differ).

**Comment by machinateur** [comment]
I'll close this, as #33 just got merged.
