### ISSUE TITLE
Error when using tabs-reopen.sh

### ISSUE THREAD

**Issue by LLLOOOMMM** [machinateur/android-chrome-tab-transfer#26]
Hello,

when using the tabs-reopen.sh script, I get the following output and nothing happens on the phone.

`Using unsafe HTTP verb GET to invoke /json/new. This action supports only PUT verb.`

This message is repeated for every tab that should be reopend.
I had no issues saving the tabs from my old phone.

I'm running the script on Ubuntu 23.04, PHP 8.1.12ubuntu4.3, Android Debug Bridge version 1.0.41

I'm trying to reopen the tabs on a Pixel 8 Pro running Android 14.

If you need any more logs or information, I'm happy to provide them.

Best regards

**Comment by machinateur** [comment]
The method was changed back in march this year:

- [Internet Archive - March 06 / 2023](https://web.archive.org/web/20230306070407/https://chromedevtools.github.io/devtools-protocol/#get-jsonnewurl)
- [Internet Archive - March 12 / 2023](https://web.archive.org/web/20230312144143/https://chromedevtools.github.io/devtools-protocol/#get-jsonnewurl)

The [current version of the docs](https://chromedevtools.github.io/devtools-protocol/#get-jsonnewurl) does indeed state `PUT` as the endpoint method.

---

I just merged #24 to fix this.
