### ISSUE TITLE
Tabs reopen in random order

### ISSUE THREAD

**Issue by JonathanLennox** [machinateur/android-chrome-tab-transfer#28]
When I reopened my tabs, the tabs opened on my new phone were in an apparently random order compared to the tabs on my old phone.

Chrome 120 in both cases; transferring from a Pixel 3a running Android 12 to a Pixel 8 running Android 14.

Workaround: I can manually edit the tabs-reopen.sh file to fix this.

**Comment by machinateur** [comment]
This is probably an issue with the underlying [Chrome HTTP API endpoint](https://developer.chrome.com/docs/devtools/remote-debugging#adb), which is used to collect the open tabs.

This tool doesn't transform the received data in any way, except for iterating over the entries in order. If they're already coming back in a seemingly random order, I don't think anything can be done about it.

I will re-check with my own device(s) regardless. Thanks for reporting!

**Comment by machinateur** [comment]
Added a new section in `README.md` addressing the tab order and groups.
